{
 "title": "Cassandra",
 "description": "Monitoring Cassandra with Prometheus using JXM exporter",
 "tags": [ "cassandra" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(up{job=~\".*mes-sgok-omp-prod.*\"}, instance)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ClientWrite avg duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Write\"} > 0"
    }
   ]
  },
  {
   "title": "ClientRead avg duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Read\"} > 0"
    }
   ]
  },
  {
   "title": "Unavailable exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({clientrequest=~\"Read|Write\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Pending threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cassandra_connection_totaltimeouts{instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Timeout exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_timeouts{clientrequest=~\"Write|Read\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"} / jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "OldGen GC duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\",gc=\"ConcurrentMarkSweep\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\",gc=\"ConcurrentMarkSweep\"}[$interval])"
    }
   ]
  },
  {
   "title": "ParNew GC duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\",gc=\"ParNew\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\",gc=\"ParNew\"}[$interval])"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Writes / sec ALL Nodes",
   "type": "graph",
   "description": "Write requests per second\t",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{type=~\"Write.*\"}[1m]) > 0",
     "legendFormat": "{{instance}}: {{type}}"
    }
   ]
  },
  {
   "title": "Reads / sec ALL Nodes",
   "type": "graph",
   "description": "Read requests per second",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{type=~\"Read.*\"}[5m]) > 0",
     "legendFormat": "{{instance}}: {{type}}"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Coordinator level stats (data can be R/W using other nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writes / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_latency_count{instance=\"$instance\",type=~\"Write.*\"}[$interval]) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Reads / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_latency_count{instance=\"$instance\",type=~\"Read.*\"}[$interval]) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Avg write latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Write.*\"} > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Avg read latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Read.*\"} > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "95thPercentile write latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"$instance\",type=~\"Write.*\"} > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "95thPercentile read latency ALL Nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"172.23.48.132:7070\",type=~\"Read.*\"} > 0",
       "legendFormat": "172.23.48.132:{{type}}"
      },
      {
       "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"172.23.48.133:7070\",type=~\"Read.*\"} > 0",
       "legendFormat": "172.23.48.133:{{type}}"
      },
      {
       "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"172.23.48.134:7070\",type=~\"Read.*\"} > 0",
       "legendFormat": "172.23.48.134:{{type}}"
      },
      {
       "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"172.23.48.135:7070\",type=~\"Read.*\"} > 0",
       "legendFormat": "172.23.48.135:{{type}}"
      },
      {
       "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"172.23.48.136:7070\",type=~\"Read.*\"} > 0",
       "legendFormat": "172.23.48.136:{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests to R/W on current node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writes \\ sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_table_writelatency_count{instance=~\"$instance\",keyspace!~\"system.*|eit\"}[$interval]) > 0",
       "legendFormat": "{{keyspace}}: {{table}}"
      }
     ]
    },
    {
     "title": "Reads \\ sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_table_readlatency_count{instance=~\"$instance\",keyspace!~\"system.*|eit\"}[$interval]) > 0",
       "legendFormat": "{{keyspace}}: {{table}}"
      }
     ]
    },
    {
     "title": "Avg write latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_writelatency_mean{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0",
       "legendFormat": "{{keyspace}}: {{table}}"
      }
     ]
    },
    {
     "title": "Avg read latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_readlatency_mean{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0",
       "legendFormat": "{{keyspace}}: {{table}}"
      }
     ]
    },
    {
     "title": "95thPercentile write latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_writelatency_95thpercentile{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0",
       "legendFormat": "{{keyspace}}: {{table}}"
      }
     ]
    },
    {
     "title": "95thPercentile read latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_readlatency_95thpercentile{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0",
       "legendFormat": "{{keyspace}}: {{table}}"
      }
     ]
    },
    {
     "title": "Keyspace Range latency $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_rangelatency_mean{instance=\"$instance\"}",
       "legendFormat": "RangeLatency"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{instance=\"$instance\"}[$interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC avg time $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\"}[$interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "Heap usage $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"}",
       "legendFormat": "Used heap size"
      },
      {
       "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}",
       "legendFormat": "Max heap size"
      }
     ]
    },
    {
     "title": "Non-Heap usage $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"nonheap\",instance=\"$instance\"}",
       "legendFormat": "Used non-heap size"
      },
      {
       "expr": "jvm_memory_bytes_committed{area=\"nonheap\",instance=\"$instance\"}",
       "legendFormat": "Commited non-heap size"
      }
     ]
    },
    {
     "title": "Memory Pool used $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Threads count $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{instance=\"$instance\"}",
       "legendFormat": "Threads count"
      }
     ]
    },
    {
     "title": "Open file descriptors $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unavailable exceptions / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_unavailables[$interval]) > 0",
       "legendFormat": "{{clientrequest}}"
      }
     ]
    },
    {
     "title": "Timeout exceptions / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_timeouts[$interval]) > 0",
       "legendFormat": "{{clientrequest}}"
      }
     ]
    },
    {
     "title": "Connection timeouts / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_connection_totaltimeouts[$interval]) > 0",
       "legendFormat": "Connection timeouts"
      }
     ]
    },
    {
     "title": "Storage exceptions / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_storage_exceptions[$interval])",
       "legendFormat": "Expections"
      }
     ]
    },
    {
     "title": "Speculative retries / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_columnfamily_speculativeretries{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    }
   ]
  },
  { "title": "DIsk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top20 tables by size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(cassandra_columnfamily_totaldiskspaceused{keyspace=~\".+\",instance=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_load{instance=~\"172.23.48.132:7070\"}",
     "legendFormat": "172.23.48.132"
    },
    {
     "expr": "cassandra_storage_load{instance=~\"172.23.48.133:7070\"}",
     "legendFormat": "172.23.48.133"
    },
    {
     "expr": "cassandra_storage_load{instance=~\"172.23.48.134:7070\"}",
     "legendFormat": "172.23.48.134"
    },
    {
     "expr": "cassandra_storage_load{instance=~\"172.23.48.135:7070\"}",
     "legendFormat": "172.23.48.135"
    },
    {
     "expr": "cassandra_storage_load{instance=~\"172.23.48.136:7070\"}",
     "legendFormat": "172.23.48.136"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top10 SSTables count $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(10,cassandra_columnfamily_livesstablecount{keyspace=~\".+\",instance=~\"$instance\"}) > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    },
    {
     "title": "Pending tasks count $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "cassandra_compaction_pendingtasks{instance=~\"$instance\"}",
       "legendFormat": "Pending tasks"
      }
     ]
    },
    {
     "title": "Completed tasks count $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_compaction_completedtasks{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Completed tasks"
      }
     ]
    },
    {
     "title": "Bytes compacted $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_compaction_bytescompacted{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Bytes compacted"
      }
     ]
    },
    {
     "title": "Completed compactions $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_compaction_totalcompactionscompleted{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Compactions completed"
      }
     ]
    },
    {
     "title": "SSTablesPerRead $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_columnfamily_sstablesperreadhistogram{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client count $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_client_connectednativeclients{instance=\"$instance\"}",
       "legendFormat": "Native"
      },
      {
       "expr": "cassandra_client_connectedthriftclients{instance=\"$instance\"}",
       "legendFormat": "Thrift"
      }
     ]
    }
   ]
  },
  {
   "title": "Hinted handoff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total hints / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_storage_totalhints{instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "Total hints count"
      }
     ]
    },
    {
     "title": "Total hints in progress / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_storage_totalhintsinprogress{instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "Total hints in progress"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloom filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "False positives $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_bloomfilterfalsepositives{keyspace=~\".+\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    },
    {
     "title": "False ratio $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_bloomfilterfalseratio{keyspace=~\".+\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    },
    {
     "title": "Disk usage $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_bloomfilterdiskspaceused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    },
    {
     "title": "OffHeap memory used $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_bloomfilteroffheapmemoryused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed tasks / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_threadpools_completedtasks{instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "{{threadpools}}"
      }
     ]
    },
    {
     "title": "Pending tasks / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_threadpools_pendingtasks{instance=~\"$instance\"} > 0",
       "legendFormat": "{{threadpools}}"
      }
     ]
    },
    {
     "title": "Dropped messages / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_droppedmessage_dropped{instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "{{droppedmessage}}"
      }
     ]
    },
    {
     "title": "Active tasks $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_threadpools_activetasks{instance=~\"$instance\"} > 0",
       "legendFormat": "{{threadpools}}"
      }
     ]
    },
    {
     "title": "Total blocked tasks / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_threadpools_totalblockedtasks{instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "{{threadpools}}"
      }
     ]
    },
    {
     "title": "Currently blocked tasks $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_threadpools_currentlyblockedtasks{instance=~\"$instance\"} > 0",
       "legendFormat": "{{threadpools}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Key cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "KeyCache Hit Rate $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_cache_hitrate{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cache size $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_cache_size{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cache hits / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_cache_hits{instance=\"$instance\"}[$interval])",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cache requests / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_cache_requests{instance=\"$instance\"}[$interval])",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cache entries $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_cache_entries{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memtables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top10 memtables by table size $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum(cassandra_columnfamily_memtablelivedatasize{keyspace=~\".+\",instance=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    },
    {
     "title": "Memtables columns count $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_memtablecolumnscount{keyspace=~\".+\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    },
    {
     "title": "Total memtables size $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_memtableonheapsize{keyspace=\"\",instance=~\"$instance\"}",
       "legendFormat": "OnHeap"
      },
      {
       "expr": "sum(cassandra_columnfamily_memtableoffheapsize{keyspace=\"\",instance=~\"$instance\"})",
       "legendFormat": "OffHeap"
      }
     ]
    },
    {
     "title": "Memtables switch count / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_columnfamily_memtableswitchcount{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CQL regular statements / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_cql_regularstatementsexecuted{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Regular statements"
      }
     ]
    },
    {
     "title": "CQL prepared statements $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_cql_preparedstatementsexecuted{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Prepared statements"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshots size $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_snapshotssize{keyspace=~\".+\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    }
   ]
  }
 ]
}